
name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -e .
          pip install pytest
      - name: Test
        run: |
          source .venv/bin/activate
          pytest -q
